#!/bin/bash

red='\x1B[0;31m'
gray='\x1B[0;30m'
NC='\x1B[0m'

tput civis

function finish {
  tput cnorm
}

trap finish EXIT

readonly leader="                    "

clear
echo -e "\n\n\n$leader${red}ready?${NC}"
sleep 1

DONE=false

while read LINE; do

  if [ -z "$LINE" ]; then
    continue
  fi

  for word in $LINE ¶ ; do
    clear

    wordlen=${#word}

    if [ $wordlen = 1 ]; then
      prefixlen=0
    elif [ $wordlen -le 3 ]; then
      prefixlen=1
    else
      prefixlen=$(($wordlen / 2 - 1))
    fi

    prelenpp=$(($prefixlen + 1))
    leaderlen=$((20 - $prefixlen))

    echo -ne "\n\n$leader${gray}|${NC}\n${leader:0:$leaderlen}"
    echo -e "${word:0:$prefixlen}${red}${word:$prefixlen:1}${NC}${word:$prelenpp}\n$leader${gray}|${NC}"

    if [ $word = "¶" ]; then
      sleep "0.5"
    else
      sleeplen=$((130 + 7 * $wordlen))
      sleep "0.$sleeplen"
    fi
  done
done

echo "whew :)"
