#!/bin/bash
set -e
red='\x1B[0;31m'
gray='\x1B[0;30m'
NC='\x1B[0m'

tput civis

function finish {
  tput cnorm
}

trap finish EXIT

function leader {
  n=$(( $(tput cols) / 2 - $1 - 1 ))
  s=$(printf "%-${n}s" " ")
  echo -n "${s}"
}

clear
ready_leader=$(leader 2)
echo -e "\n\n\n${ready_leader}${red}ready?${NC}"
sleep 1

DONE=false

while IFS='' read -r LINE || [[ -n "$LINE" ]]; do

  if [ -z "$LINE" ]; then
    continue
  fi

  ARRAY=($LINE ¶)

  for i in "${!ARRAY[@]}" ; do

    lastword=`[[ $(($i - 1)) -gt 0 ]] && echo -n ${ARRAY[$(($i - 1))]} || echo -n ""`
    word="${ARRAY[$i]}"
    nextword=`[[ $(($i + 1)) -lt ${#ARRAY[@]} ]] && echo -n ${ARRAY[$(($i + 1))]} || echo -n ""`

    lastwordlen=${#lastword}
    wordlen=${#word}

    if [ $wordlen = 1 ]; then
      prefixlen=0
    elif [ $wordlen -le 3 ]; then
      prefixlen=1
    else
      prefixlen=$(( $wordlen / 2 - 1 ))
    fi

    prelenpp=$(($prefixlen + 1))
    word_leader=$(leader $(( $prefixlen + 1 + $lastwordlen )))
    crosshair_leader=$(leader 0)

    msg="\n\n${crosshair_leader}${gray}|${NC}\n"
    msg="${msg}${word_leader}${gray}${lastword}${NC} "
    msg="${msg}${word:0:$prefixlen}${red}${word:$prefixlen:1}${NC}${word:$prelenpp}"
    msg="${msg} ${gray}${nextword}${NC}\n"
    msg="${msg}${crosshair_leader}${gray}|${NC}"
    clear
    echo -e "${msg}"

    if [ $word = "¶" ]; then
      sleep "0.5"
    else
      sleeplen=$((130 + 7 * $wordlen))
      sleep "0.$sleeplen"
    fi
  done
done
